services:

    api:
      image: ai-support-agent
      build: .
      container_name: ai_support_api
      command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
      ports:
        - "8000:8000"
      restart: unless-stopped

    web:
      image: ai-support-agent
      container_name: ai_support_web
      command: streamlit run src/webapp/app.py --server.port=8501 --server.address=0.0.0.0
      ports:
        - "8501:8501"
      depends_on:
        - api
      environment:
        - API_URL=http://api:8000/chat
      restart: unless-stopped
      
      
      
